workflows:
  ios-workflow:
    name: iOS Ilovani Yig'ish
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Paketlarni o'rnatish
        script: npm install
      - name: Kodlarni sinxronlash
        script: npx cap sync ios
      - name: iOS kutubxonalarini o'rnatish
        script: |
          cd ios/App
          pod install --repo-update
      - name: Xcode orqali yig'ish (Sertifikatsiz test)
        script: |
          cd ios/App
          xcodebuild build -workspace App.xcworkspace -scheme App -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO