# Generated by Django 6.0 on 2026-01-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Arbeiter'), ('customer', 'Kunde')], default='customer', max_length=20),
        ),
    ]
