# Generated by Django 6.0 on 2026-01-09 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Wartend'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Wartend'), ('processing', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='pending', max_length=15),
        ),
    ]
