# Generated by Django 6.0 on 2026-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_orderitem_completed_quantity_orderitem_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='completed_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='worker',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Ishchi'), ('customer', 'Mijoz')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
