# Generated by Django 6.0 on 2026-01-12 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='operations.shift')),
            ],
        ),
    ]
