# Generated by Django 6.0 on 2026-01-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_shiftreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_items', to='operations.shift'),
        ),
    ]
