# Generated by Django 5.2.10 on 2026-02-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_orderitem_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='current_stock',
            field=models.FloatField(default=0, verbose_name='Aktueller Lagerbestand (kg)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target_amount',
            field=models.FloatField(default=0, verbose_name='Soll-Bestand (kg)'),
        ),
    ]
