# Generated by Django 5.2.10 on 2026-02-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_menuitem_current_stock_menuitem_target_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='target_amount',
        ),
        migrations.CreateModel(
            name='Lager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.FloatField(default=0, verbose_name='Aktueller Lagerbestand (kg)')),
                ('target_amount', models.FloatField(default=0, verbose_name='Soll-Bestand (kg)')),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='operations.menuitem')),
            ],
        ),
    ]
