# Generated by Django 5.2.10 on 2026-02-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lager',
            name='target_amount',
        ),
    ]
