# Generated by Django 5.2.10 on 2026-02-15 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_remove_lager_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='product_type',
            field=models.CharField(default='Roh', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
