# Generated by Django 5.2.10 on 2026-02-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_shiftreport_created_at_shiftreport_product_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'produkt_type')},
        ),
    ]
