# Generated by Django 5.2.10 on 2026-08-16 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_menuitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_production_target_kg', models.FloatField(default=30000.0, help_text='Tägliches Produktionsziel in kg (z.B. 30000 für 30 Tonnen)', verbose_name='Tägliches Produktionsziel (kg)')),
                ('beutels_per_palette', models.PositiveIntegerField(default=50, help_text='Anzahl der Beutel (Säcke), die eine Palette bilden', verbose_name='Beutel pro Palette')),
                ('buro_working_start', models.TimeField(default=datetime.time(8, 0), verbose_name='Büro Arbeitsbeginn')),
                ('buro_working_end', models.TimeField(default=datetime.time(17, 0), verbose_name='Büro Arbeitsende')),
                ('production_working_start', models.TimeField(default=datetime.time(6, 0), verbose_name='Produktion Arbeitsbeginn')),
                ('production_working_end', models.TimeField(default=datetime.time(22, 0), verbose_name='Produktion Arbeitsende')),
                ('next_day_cutoff_time', models.TimeField(default=datetime.time(22, 0), help_text='Bestellungen nach dieser Uhrzeit werden automatisch für den Folgetag eingeplant', verbose_name='Cut-off-Zeit für nächsten Tag')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabrikeinstellung',
                'verbose_name_plural': 'Fabrikeinstellungen',
            },
        ),
    ]
