# Generated by Django 5.2.10 on 2026-08-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_factorysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorysettings',
            name='beutels_per_palette',
        ),
        migrations.RemoveField(
            model_name='factorysettings',
            name='daily_production_target_kg',
        ),
        migrations.AddField(
            model_name='factorysettings',
            name='hourly_production_target_kg',
            field=models.FloatField(default=1250.0, help_text='Produktionskapazität pro Stunde in kg (z.B. 1250 kg/h entspricht 30.000 kg pro 24h)', verbose_name='Stündliches Produktionsziel (kg/h)'),
        ),
    ]
