# Generated by Django 5.2.10 on 2026-08-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_remove_factorysettings_beutels_per_palette_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorysettings',
            name='hourly_production_target_kg',
        ),
        migrations.AddField(
            model_name='factorysettings',
            name='kg_per_palette',
            field=models.FloatField(default=625.0, help_text='Gewicht einer einzelnen Palette in kg (z.B. 625 kg)', verbose_name='Gewicht pro Palette (kg)'),
        ),
        migrations.AddField(
            model_name='factorysettings',
            name='palettes_per_hour',
            field=models.FloatField(default=2.0, help_text='Anzahl der produzierten Paletten pro Stunde (z.B. 2.0)', verbose_name='Paletten pro Stunde'),
        ),
    ]
