# Generated by Django 5.2.10 on 2026-08-17 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_remove_factorysettings_hourly_production_target_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Abholzeit / Pickup Time'),
        ),
    ]
