# Generated by Django 5.2.10 on 2026-09-02 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_order_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yetkazib berish sanasi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Mitarbeiter'), ('customer', 'Kunde')], default='customer', max_length=20),
        ),
    ]
